### PR TITLE
tests whether the photos change (duration to be finessed)

### PR DESCRIPTION
**Pull request by rjmk**
@Danwhy looks good?

### CODE REVIEW

**Comment by Danwhy** [comment]
looks good, but there is nothing with an id of 'photos' in the html

**Comment by rjmk** [comment]
@Danwhy why can't this be merged automatically?

**Comment by Danwhy** [comment]
I don't know. It could have originally, but something has changed since

**Comment by rjmk** [comment]
@Danwhy :)

**Pull request merged**
